spring:
  jta:
    enabled: true
  datasource:
    first:
      jdbcUrl: jdbc:postgresql://postgres:5432/sample_book_manager
      username: test
      password: test
      driverClassName: org.postgresql.Driver
    second:
      jdbcUrl: jdbc:postgresql://postgres:5432/sample_book_manager_other
      username: test
      password: test
      driverClassName: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379
  devtools:
    livereload:
      enabled: true
logging:
  level:
    com:
      atomikos: DEBUG
    root: INFO
atomikos:
  properties:
    max-timeout: 900000
