spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sample_book_manager
    username: test
    password: test
    driverClassName: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    root: INFO
